export const PAGE_CONFIGS = {
  category: {
    title: "Category",
    summaryLabel: "Categories",
    actionLabel: "New Category",
    searchPlaceholder: "Search category",
    filters: [],
    searchFields: [
      "name",
      "hierarchyPath",
      "connectedCatalogDisplay",
      "connectedCatalogSearch",
    ],
    columns: [
      {
        key: "name",
        label: "Category Name",
        type: "link",
        subtitleKey: "hierarchyDisplay",
        sortable: true,
      },
      {
        key: "connectedCatalogDisplay",
        label: "Connected Catalog",
        type: "text",
        contentClassName: "lab-table__ellipsis-copy",
      },
      { key: "actions", label: "", type: "delete" },
    ],
  },
  unit: {
    title: "Unit",
    summaryLabel: "Units",
    actionLabel: "New Unit",
    searchPlaceholder: "Search unit",
    filters: [],
    searchFields: [
      "name",
      "precisionDisplay",
      "connectedCatalogDisplay",
      "connectedCatalogSearch",
    ],
    columns: [
      { key: "name", label: "Unit Name", type: "link", sortable: true, width: "240px" },
      { key: "precisionDisplay", label: "Precision", type: "text", sortable: true, width: "120px" },
      {
        key: "connectedCatalogDisplay",
        label: "Connected Catalog",
        type: "text",
        contentClassName: "lab-table__ellipsis-copy unit-connected-catalog-content",
        thClassName: "unit-connected-catalog-th",
      },
      { key: "actions", label: "", type: "delete" },
    ],
  },
  modifier: {
    title: "Modifier",
    summaryLabel: "Modifiers",
    actionLabel: "New Modifier",
    searchPlaceholder: "Search modifier",
    filters: [],
    searchFields: [
      "name",
      "modifierOptionsDisplay",
      "modifierOptionsSearch",
      "connectedCatalogDisplay",
      "connectedCatalogSearch",
    ],
    columns: [
      { key: "name", label: "Modifier Name", type: "link", sortable: true },
      {
        key: "modifierOptionsDisplay",
        label: "Modifier Options",
        type: "text",
        contentClassName: "lab-table__ellipsis-copy",
      },
      {
        key: "connectedCatalogDisplay",
        label: "Connected Catalog",
        type: "text",
        contentClassName: "lab-table__ellipsis-copy",
      },
      {
        key: "availability",
        label: "Availability",
        type: "component",
        thClassName: "lab-table__cell--center",
        tdClassName: "lab-table__cell--center",
        width: "120px",
      },
      { key: "actions", label: "", type: "delete" },
    ],
  },
  "pricing-rule": {
    title: "Pricing Rule",
    summaryLabel: "Rules",
    actionLabel: "New Special Pricing Rule",
    searchPlaceholder: "Search",
    filters: [],
    searchFields: ["name", "timeWindowSearch"],
    columns: [
      { key: "name", label: "Rule Name", type: "link", sortable: true },
      { key: "timeWindowSearch", label: "Time Window", type: "text", sortable: true },
      { key: "actions", label: "", type: "delete" },
    ],
  },
  "selling-time": {
    title: "Selling Time",
    summaryLabel: "Selling Times",
    actionLabel: "New Selling Time",
    searchPlaceholder: "Search selling time",
    filters: [],
    searchFields: ["name", "dayDisplay"],
    columns: [
      { key: "name", label: "Selling Time Name", type: "link" },
      { key: "dayDisplay", label: "Day", type: "text" },
      { key: "actions", label: "", type: "delete" },
    ],
  },
  "business-unit": {
    title: "Entity",
    actionLabel: "New Entity",
    searchPlaceholder: "Search entity",
    filters: [{ key: "status", options: ["All", "Active", "Inactive"] }],
    searchFields: ["name", "location"],
    columns: [
      { key: "name", label: "Entity Name", type: "link" },
      { key: "location", label: "Location", type: "text" },
      { key: "tables", label: "Tables", type: "text" },
      { key: "manager", label: "Manager", type: "text" },
      { key: "status", label: "Status", type: "status" },
      { key: "actions", label: "", type: "delete" },
    ],
  },
  "user-list": {
    title: "User List",
    actionLabel: "Invite User",
    searchPlaceholder: "Search user",
    filters: [
      { key: "status", options: ["All", "Active", "Inactive"] },
      {
        key: "role",
        options: ["All", "Owner", "Manager", "Cashier", "Inventory"],
      },
    ],
    searchFields: ["name", "role", "branch"],
    columns: [
      { key: "name", label: "User Name", type: "link" },
      { key: "role", label: "Role", type: "text" },
      { key: "branch", label: "Branch", type: "text" },
      { key: "lastSeen", label: "Last Seen", type: "text" },
      { key: "status", label: "Status", type: "status" },
      { key: "actions", label: "", type: "delete" },
    ],
  },
  "role-access": {
    title: "Role Access",
    summaryLabel: "Roles",
    actionLabel: "New Role Access",
    searchPlaceholder: "Search role access",
    filters: [],
    searchFields: ["name", "members", "description"],
    columns: [
      { key: "name", label: "Role Name", type: "link" },
      { key: "members", label: "Member", type: "text" },
      { key: "description", label: "Description", type: "text" },
      { key: "actions", label: "", type: "delete" },
    ],
  },
  "device-management": {
    title: "Device",
    actionLabel: "New Device",
    searchPlaceholder: "Search device",
    filters: [
      {
        key: "deviceType",
        label: "Device Type",
        mode: "multi",
        options: [
          "Point of Sales (POS)",
          "Point of Sales (POS)",
          "Kitchen Display System (KDS)",
          "Point of Sales (POS)",
          "Kiosk",
          "Printer",
        ],
      },
      {
        key: "status",
        label: "Status",
        mode: "multi",
        options: ["Connected", "Pending", "Expired", "Disconnected"],
      },
    ],
    searchFields: ["deviceName", "deviceType", "connectedDevices"],
    columns: [
      {
        key: "deviceName",
        label: "Device Name",
        type: "link",
      },
      {
        key: "deviceType",
        label: "Device Type",
        type: "text",
      },
      {
        key: "deviceConnected",
        label: "Device Connected",
        type: "text",
        contentClassName: "lab-table__ellipsis-copy",
      },
      {
        key: "lastActive",
        label: "Last Active",
        type: "text",
      },
      {
        key: "addedByName",
        label: "Added By",
        type: "link",
        subtitleKey: "addedByRole",
      },
      {
        key: "status",
        label: "Status",
        type: "status",
      },
      { key: "actions", label: "", type: "delete" },
    ],
  },
  "grouped-device": {
    title: "KDS Group",
    actionLabel: "New KDS Group",
    searchPlaceholder: "Search KDS group",
    filters: [],
    searchFields: ["name", "deviceListDisplay", "catalogListDisplay"],
    columns: [
      { key: "name", label: "KDS Group Name", type: "link", sortable: true },
      {
        key: "deviceListDisplay",
        label: "Device List",
        type: "text",
        contentClassName: "lab-table__ellipsis-copy",
      },
      {
        key: "catalogListDisplay",
        label: "Catalog List",
        type: "text",
        contentClassName: "lab-table__ellipsis-copy",
      },
      { key: "actions", label: "", type: "delete" },
    ],
  },
};
