import { createDefaultPricingOverrideSections, createSpecialPricingRuleRecord, applyPricingRuleMaximums, createPricingOverrideSections, syncAssignedUnitsWithPricingSections } from "./pricingUtils.js";
import { createCatalogSeedRecord, createCatalogPhotoSetForRecord, createCatalogAssignedUnits } from "./catalogBuildUtils.js";
import { createRolePermissions } from "./roleUtils.js";
import { ALL_ROLE_PERMISSION_MODULES } from "./deviceGroupUtils.js";
import { ALL_SELLING_TIME_DAY_LABELS, SELLING_TIME_DAY_OPTIONS, UNIT_PRECISION_OPTIONS, BUSINESS_UNIT_ASSIGNMENT_GROUPS } from "../constants/catalog.js";
import { DEFAULT_PRICING_OVERRIDE_MAXIMUMS, PRICING_OVERRIDE_GROUPS, PRICING_RULE_MONTH_LABELS } from "../constants/pricing.js";
import { MENU, DETAIL_PAGE_PARENT } from "../constants/menu.js";
import { PAGE_CONFIGS } from "../constants/pageConfigs.js";

export function createInitialDataStore() {
  const defaultPricingOverrideSections = createDefaultPricingOverrideSections();
  const pricingRuleSeedRecords = [
    createSpecialPricingRuleRecord({
      id: "pr-001",
      name: "Eid Surcharge 2",
      startDate: "01/04/2026, 00:00",
      endDate: "01/04/2026, 23:59",
      overrides: applyPricingRuleMaximums(createPricingOverrideSections(), {
        "catalog-unit-central-jakarta": "5",
        "catalog-unit-bandung": "5",
        "catalog-unit-surabaya": "5",
        "catalog-unit-bali": "5",
        "modifier-unit-central-jakarta": "5",
        "modifier-unit-bandung": "5",
        "modifier-unit-surabaya": "5",
        "modifier-unit-bali": "5",
      }),
    }),
    createSpecialPricingRuleRecord({
      id: "pr-002",
      name: "Eid Surcharge 1",
      startDate: "01/04/2026, 00:00",
      endDate: "07/04/2026, 23:59",
      overrides: applyPricingRuleMaximums(createPricingOverrideSections(), {
        "catalog-unit-central-jakarta": "3",
        "catalog-unit-bandung": "3",
        "catalog-unit-surabaya": "3",
        "catalog-unit-bali": "0",
        "modifier-unit-central-jakarta": "2",
        "modifier-unit-bandung": "2",
        "modifier-unit-surabaya": "2",
        "modifier-unit-bali": "0",
      }),
    }),
  ];

  return {
    catalog: [
      createCatalogSeedRecord({
        id: "cat-001",
        name: "Special Package",
        category: "Uncategorized",
        basePrice: 155000,
        price: "155000",
        priceRule: "Standard",
        sellingTime: "All Day",
        availability: true,
        type: "package",
        allowOverridePrice: true,
        photos: createCatalogPhotoSetForRecord(
          {
            id: "cat-001",
            name: "Special Package",
            category: "Uncategorized",
            type: "package",
          },
          5
        ),
        packageItems: [
          { id: "cat-001-package-1", catalogId: "Burger Supreme", qty: "1" },
          { id: "cat-001-package-2", catalogId: "Iced Coffee", qty: "1" },
        ],
        assignedUnits: syncAssignedUnitsWithPricingSections(
          createCatalogAssignedUnits(["unit-central-jakarta", "unit-surabaya"], {
            "unit-central-jakarta": {
              overridePrice: "IDR 155.000",
            },
          }),
          "catalog",
          defaultPricingOverrideSections
        ),
      }),
      createCatalogSeedRecord({
        id: "cat-002",
        name: "Burger Supreme",
        category: "Main Course",
        basePrice: 125000,
        price: "125000",
        priceRule: "Override Enabled",
        sellingTime: "All Day",
        availability: true,
        photos: createCatalogPhotoSetForRecord(
          {
            id: "cat-002",
            name: "Burger Supreme",
            category: "Main Course",
            type: "single",
          },
          3
        ),
        modifier: ["Extra Cheese", "Cooking Level"],
        allowOverridePrice: true,
        assignedUnits: syncAssignedUnitsWithPricingSections(
          createCatalogAssignedUnits(["unit-central-jakarta"], {
            "unit-central-jakarta": {
              overridePrice: "IDR 137.500",
            },
          }),
          "catalog",
          defaultPricingOverrideSections
        ),
      }),
      createCatalogSeedRecord({
        id: "cat-003",
        name: "Linguine Pesto",
        category: "Main Course",
        basePrice: 150000,
        price: "150000",
        priceRule: "Chef Pick",
        sellingTime: "All Day",
        availability: true,
        photos: createCatalogPhotoSetForRecord(
          {
            id: "cat-003",
            name: "Linguine Pesto",
            category: "Main Course",
            type: "single",
          },
          2
        ),
        modifier: ["Extra Cheese"],
      }),
      createCatalogSeedRecord({
        id: "cat-004",
        name: "Lava Cake",
        category: "Desserts",
        basePrice: 85000,
        price: "85000",
        priceRule: "Dessert Boost",
        sellingTime: "All Day",
        availability: true,
        photos: createCatalogPhotoSetForRecord(
          {
            id: "cat-004",
            name: "Lava Cake",
            category: "Desserts",
            type: "single",
          },
          2
        ),
      }),
      createCatalogSeedRecord({
        id: "cat-005",
        name: "Caesar Salad",
        category: "Appetizers",
        basePrice: 100000,
        price: "100000",
        priceRule: "Standard",
        sellingTime: "All Day",
        availability: true,
        photos: createCatalogPhotoSetForRecord(
          {
            id: "cat-005",
            name: "Caesar Salad",
            category: "Appetizers",
            type: "single",
          },
          2
        ),
      }),
      createCatalogSeedRecord({
        id: "cat-006",
        name: "Truffle Fries",
        category: "Appetizers",
        basePrice: 60000,
        price: "60000",
        priceRule: "Snack Time",
        sellingTime: "All Day",
        availability: false,
        photos: createCatalogPhotoSetForRecord(
          {
            id: "cat-006",
            name: "Truffle Fries",
            category: "Appetizers",
            type: "single",
          },
          1
        ),
      }),
      createCatalogSeedRecord({
        id: "cat-007",
        name: "Iced Coffee",
        category: "Beverages",
        basePrice: 35000,
        price: "35000",
        priceRule: "Happy Hour",
        sellingTime: "All Day",
        availability: true,
        photos: createCatalogPhotoSetForRecord(
          {
            id: "cat-007",
            name: "Iced Coffee",
            category: "Beverages",
            type: "single",
          },
          1
        ),
        modifier: ["Sugar Level", "Ice Preference"],
      }),
    ],
    category: [
      {
        id: "cg-000",
        name: "Uncategorized",
        parentCategory: "",
        sellingTime: "All Day",
        color: "#F9EB9E",
        isDefault: true,
      },
      {
        id: "cg-pkg-000",
        name: "Package",
        parentCategory: "",
        sellingTime: "All Day",
        color: "#D1C0F6",
        isDefault: true,
      },
      {
        id: "cg-001",
        name: "Main Course",
        parentCategory: "",
        sellingTime: "All Day",
        color: "#F5BCBC",
      },
      {
        id: "cg-002",
        name: "Appetizers",
        parentCategory: "",
        sellingTime: "All Day",
        color: "#F6D3B8",
      },
      {
        id: "cg-003",
        name: "Beverages",
        parentCategory: "",
        sellingTime: "Breakfast",
        color: "#A5EEE6",
      },
      {
        id: "cg-004",
        name: "Desserts",
        parentCategory: "",
        sellingTime: "Lunch Rush",
        color: "#F9C0DD",
      },
      {
        id: "cg-005",
        name: "Seasonal",
        parentCategory: "",
        sellingTime: "Late Night",
        color: "#CDE7C9",
      },
    ],
    unit: [
      { id: "unit-uom-001", name: "Pcs", precision: "1", isDefault: true },
      { id: "unit-uom-002", name: "Kilogram (kg)", precision: ".000" },
      { id: "unit-uom-003", name: "Gram (gr)", precision: "1" },
      { id: "unit-uom-004", name: "Liter (L)", precision: ".00" },
      { id: "unit-uom-005", name: "Milliliter (ml)", precision: "1" },
      { id: "unit-uom-006", name: "Pack", precision: "1" },
    ],
    modifier: [
      {
        id: "md-001",
        name: "Extra Cheese",
        modifierOptions: "4 options",
        connectedCatalog: "12 catalog",
        minimumSelection: "0",
        maximumSelection: "4",
        allowOverridePrice: false,
        assignedUnits: [],
        options: [
          { id: "md-001-opt-1", name: "Mozzarella", additionalPrice: "12000" },
          { id: "md-001-opt-2", name: "Cheddar", additionalPrice: "10000" },
          { id: "md-001-opt-3", name: "Parmesan", additionalPrice: "14000" },
          { id: "md-001-opt-4", name: "Burrata", additionalPrice: "18000" },
        ],
        connectedCatalogItems: ["Burger Supreme", "Linguine Pesto"],
      },
      {
        id: "md-002",
        name: "Cooking Level",
        modifierOptions: "3 options",
        connectedCatalog: "6 catalog",
        minimumSelection: "1",
        maximumSelection: "1",
        allowOverridePrice: false,
        assignedUnits: [],
        options: [
          { id: "md-002-opt-1", name: "Rare", additionalPrice: "0", isDefault: false },
          { id: "md-002-opt-2", name: "Medium", additionalPrice: "0", isDefault: true },
          { id: "md-002-opt-3", name: "Well Done", additionalPrice: "0", isDefault: false },
        ],
        connectedCatalogItems: ["Burger Supreme"],
      },
      {
        id: "md-003",
        name: "Sugar Level",
        modifierOptions: "5 options",
        connectedCatalog: "3 catalog",
        connectedCatalogCount: 3,
        minimumSelection: "1",
        maximumSelection: "0",
        allowOverridePrice: true,
        assignedUnits: syncAssignedUnitsWithPricingSections(
          createCatalogAssignedUnits(["unit-central-jakarta", "unit-surabaya"]),
          "modifier",
          defaultPricingOverrideSections
        ),
        options: [
          { id: "md-003-opt-1", name: "0%", additionalPrice: "0", isDefault: false },
          { id: "md-003-opt-2", name: "25%", additionalPrice: "0", isDefault: false },
          { id: "md-003-opt-3", name: "50%", additionalPrice: "1000", isDefault: true },
          { id: "md-003-opt-4", name: "75%", additionalPrice: "3000", isDefault: false },
          { id: "md-003-opt-5", name: "100%", additionalPrice: "5000", isDefault: false },
        ],
        connectedCatalogItems: [
          "Burger Supreme",
          "Linguine Pesto",
          "Iced Coffee",
        ],
      },
      {
        id: "md-004",
        name: "Ice Preference",
        modifierOptions: "3 options",
        connectedCatalog: "7 catalog",
        minimumSelection: "0",
        maximumSelection: "1",
        allowOverridePrice: false,
        assignedUnits: [],
        options: [
          { id: "md-004-opt-1", name: "No Ice", additionalPrice: "0" },
          { id: "md-004-opt-2", name: "Less Ice", additionalPrice: "0" },
          { id: "md-004-opt-3", name: "Normal Ice", additionalPrice: "0" },
        ],
        connectedCatalogItems: ["Iced Coffee", "Burger Supreme"],
      },
      {
        id: "md-005",
        name: "Combo Upsize",
        modifierOptions: "2 options",
        connectedCatalog: "5 catalog",
        minimumSelection: "0",
        maximumSelection: "2",
        allowOverridePrice: false,
        assignedUnits: [],
        options: [
          {
            id: "md-005-opt-1",
            name: "Upgrade Fries",
            additionalPrice: "15000",
          },
          {
            id: "md-005-opt-2",
            name: "Upgrade Drink",
            additionalPrice: "12000",
          },
        ],
        connectedCatalogItems: ["Special Package", "Burger Supreme"],
      },
      {
        id: "md-006",
        name: "Spice Level",
        modifierOptions: "5 options",
        connectedCatalog: "4 catalog",
        minimumSelection: "1",
        maximumSelection: "1",
        allowOverridePrice: false,
        assignedUnits: [],
        options: [
          { id: "md-006-opt-1", name: "None", additionalPrice: "0", isDefault: true },
          { id: "md-006-opt-2", name: "Mild", additionalPrice: "0" },
          { id: "md-006-opt-3", name: "Medium", additionalPrice: "0" },
          { id: "md-006-opt-4", name: "Hot", additionalPrice: "0" },
          { id: "md-006-opt-5", name: "Extra Hot", additionalPrice: "0" },
        ],
        connectedCatalogItems: ["Caesar Salad", "Burger Supreme"],
      },
      {
        id: "md-007",
        name: "Sauce",
        modifierOptions: "4 options",
        connectedCatalog: "3 catalog",
        minimumSelection: "0",
        maximumSelection: "2",
        allowOverridePrice: false,
        assignedUnits: [],
        options: [
          { id: "md-007-opt-1", name: "Ketchup", additionalPrice: "0" },
          { id: "md-007-opt-2", name: "Mayonnaise", additionalPrice: "0" },
          { id: "md-007-opt-3", name: "BBQ", additionalPrice: "2000" },
          { id: "md-007-opt-4", name: "Hot Sauce", additionalPrice: "2000" },
        ],
        connectedCatalogItems: ["Burger Supreme", "Truffle Fries"],
      },
      {
        id: "md-008",
        name: "Add-on Protein",
        modifierOptions: "3 options",
        connectedCatalog: "2 catalog",
        minimumSelection: "0",
        maximumSelection: "1",
        allowOverridePrice: false,
        assignedUnits: [],
        options: [
          { id: "md-008-opt-1", name: "Egg", additionalPrice: "8000" },
          { id: "md-008-opt-2", name: "Chicken", additionalPrice: "15000" },
          { id: "md-008-opt-3", name: "Beef Patty", additionalPrice: "20000" },
        ],
        connectedCatalogItems: ["Caesar Salad", "Burger Supreme"],
      },
      {
        id: "md-009",
        name: "Portion Size",
        modifierOptions: "3 options",
        connectedCatalog: "6 catalog",
        minimumSelection: "1",
        maximumSelection: "1",
        allowOverridePrice: false,
        assignedUnits: [],
        options: [
          { id: "md-009-opt-1", name: "Small", additionalPrice: "0" },
          { id: "md-009-opt-2", name: "Regular", additionalPrice: "0", isDefault: true },
          { id: "md-009-opt-3", name: "Large", additionalPrice: "12000" },
        ],
        connectedCatalogItems: ["Truffle Fries", "Burger Supreme"],
      },
      {
        id: "md-010",
        name: "Cooking Method",
        modifierOptions: "4 options",
        connectedCatalog: "3 catalog",
        minimumSelection: "1",
        maximumSelection: "1",
        allowOverridePrice: false,
        assignedUnits: [],
        options: [
          { id: "md-010-opt-1", name: "Grilled", additionalPrice: "0", isDefault: true },
          { id: "md-010-opt-2", name: "Fried", additionalPrice: "0" },
          { id: "md-010-opt-3", name: "Steamed", additionalPrice: "0" },
          { id: "md-010-opt-4", name: "Baked", additionalPrice: "5000" },
        ],
        connectedCatalogItems: ["Burger Supreme"],
      },
      {
        id: "md-011",
        name: "Noodle Type",
        modifierOptions: "3 options",
        connectedCatalog: "2 catalog",
        minimumSelection: "1",
        maximumSelection: "1",
        allowOverridePrice: false,
        assignedUnits: [],
        options: [
          { id: "md-011-opt-1", name: "Rice Noodle", additionalPrice: "0", isDefault: true },
          { id: "md-011-opt-2", name: "Egg Noodle", additionalPrice: "0" },
          { id: "md-011-opt-3", name: "Glass Noodle", additionalPrice: "0" },
        ],
        connectedCatalogItems: ["Linguine Pesto", "Burger Supreme"],
      },
      {
        id: "md-012",
        name: "Temperature",
        modifierOptions: "3 options",
        connectedCatalog: "5 catalog",
        minimumSelection: "1",
        maximumSelection: "1",
        allowOverridePrice: false,
        assignedUnits: [],
        options: [
          { id: "md-012-opt-1", name: "Hot", additionalPrice: "0", isDefault: true },
          { id: "md-012-opt-2", name: "Cold", additionalPrice: "0" },
          { id: "md-012-opt-3", name: "Iced", additionalPrice: "3000" },
        ],
        connectedCatalogItems: ["Iced Coffee", "Burger Supreme"],
      },
      {
        id: "md-013",
        name: "Bread Type",
        modifierOptions: "4 options",
        connectedCatalog: "2 catalog",
        minimumSelection: "1",
        maximumSelection: "1",
        allowOverridePrice: false,
        assignedUnits: [],
        options: [
          { id: "md-013-opt-1", name: "White", additionalPrice: "0", isDefault: true },
          { id: "md-013-opt-2", name: "Wheat", additionalPrice: "0" },
          { id: "md-013-opt-3", name: "Sourdough", additionalPrice: "5000" },
          { id: "md-013-opt-4", name: "Brioche", additionalPrice: "8000" },
        ],
        connectedCatalogItems: ["Burger Supreme"],
      },
      {
        id: "md-014",
        name: "Milk Option",
        modifierOptions: "4 options",
        connectedCatalog: "3 catalog",
        minimumSelection: "1",
        maximumSelection: "1",
        allowOverridePrice: false,
        assignedUnits: [],
        options: [
          { id: "md-014-opt-1", name: "Full Cream", additionalPrice: "0", isDefault: true },
          { id: "md-014-opt-2", name: "Low Fat", additionalPrice: "0" },
          { id: "md-014-opt-3", name: "Oat Milk", additionalPrice: "8000" },
          { id: "md-014-opt-4", name: "Almond Milk", additionalPrice: "10000" },
        ],
        connectedCatalogItems: ["Iced Coffee", "Burger Supreme"],
      },
      {
        id: "md-015",
        name: "Extra Toppings",
        modifierOptions: "4 options",
        connectedCatalog: "4 catalog",
        minimumSelection: "0",
        maximumSelection: "4",
        allowOverridePrice: false,
        assignedUnits: [],
        options: [
          { id: "md-015-opt-1", name: "Mushroom", additionalPrice: "7000" },
          { id: "md-015-opt-2", name: "Tomato", additionalPrice: "5000" },
          { id: "md-015-opt-3", name: "Onion", additionalPrice: "4000" },
          { id: "md-015-opt-4", name: "Bacon", additionalPrice: "12000" },
        ],
        connectedCatalogItems: ["Burger Supreme", "Caesar Salad"],
      },
    ],
    "pricing-rule": pricingRuleSeedRecords,
    "selling-time": [
      {
        id: "st-001",
        name: "All Day",
        days: [...ALL_SELLING_TIME_DAY_LABELS],
      },
      {
        id: "st-002",
        name: "Breakfast",
        days: ALL_SELLING_TIME_DAY_LABELS.slice(0, 5),
      },
      {
        id: "st-003",
        name: "Lunch Rush",
        days: [...ALL_SELLING_TIME_DAY_LABELS],
      },
      {
        id: "st-004",
        name: "Late Night",
        days: ["Friday", "Saturday"],
      },
    ],
    "business-unit": [
      {
        id: "bu-001",
        name: "Labamu Central Jakarta",
        location: "SCBD, Jakarta",
        tables: "42",
        manager: "Rendra Putra",
        status: "Active",
      },
      {
        id: "bu-002",
        name: "Labamu Bandung",
        location: "Dago, Bandung",
        tables: "28",
        manager: "Nadya Putri",
        status: "Active",
      },
      {
        id: "bu-003",
        name: "Labamu Surabaya",
        location: "Pakuwon, Surabaya",
        tables: "35",
        manager: "Rizal Akbar",
        status: "Active",
      },
      {
        id: "bu-004",
        name: "Labamu Bali",
        location: "Seminyak, Bali",
        tables: "24",
        manager: "Dea Maheswari",
        status: "Inactive",
      },
    ],
    "user-list": [
      {
        id: "usr-001",
        name: "Natasha Smith",
        role: "Owner",
        branch: "HQ",
        lastSeen: "Online now",
        status: "Active",
      },
      {
        id: "usr-002",
        name: "Rendy Saputra",
        role: "Manager",
        branch: "Central Jakarta",
        lastSeen: "8 mins ago",
        status: "Active",
      },
      {
        id: "usr-003",
        name: "Salsa Mahendra",
        role: "Cashier",
        branch: "Bandung",
        lastSeen: "22 mins ago",
        status: "Active",
      },
      {
        id: "usr-004",
        name: "Dio Ramadhan",
        role: "Inventory",
        branch: "Surabaya",
        lastSeen: "1 hour ago",
        status: "Active",
      },
      {
        id: "usr-005",
        name: "Anisa Dewi",
        role: "Manager",
        branch: "Bali",
        lastSeen: "2 days ago",
        status: "Inactive",
      },
    ],
    "role-access": [
      {
        id: "rl-001",
        type: "System",
        name: "Holding Owner",
        members: "1 member",
        membersList: [
          { id: "mbr-001", name: "John Manager", email: "john.manager@restaurant.com", status: "Active" },
        ],
        description: "Full access across account controls and entity operations.",
        status: "Active",
        updated: "2 Apr 2026",
        permissions: createRolePermissions(
          Object.fromEntries(
            ALL_ROLE_PERMISSION_MODULES.map((module) => [
              module.id,
              module.permittedLevels && !module.permittedLevels.includes("full")
                ? module.permittedLevels[module.permittedLevels.length - 1]
                : "full",
            ])
          )
        ),
      },
      {
        id: "rl-002",
        type: "System",
        name: "Account Administrator",
        members: "2 members",
        membersList: [
          { id: "mbr-002", name: "Sarah Admin", email: "sarah.admin@restaurant.com", status: "Active" },
          { id: "mbr-003", name: "Mike Invited", email: "mike.invited@restaurant.com", status: "Invited" },
        ],
        description: "Manages user, role, and entity access for the main account.",
        status: "Active",
        updated: "30 Mar 2026",
        permissions: createRolePermissions({
          "user-management": {
            level: "full",
            additionalAccess: {
              suspendUser: true,
              regeneratePin: true,
              assignOtherEntities: true,
            },
          },
          "role-management": "full",
          "entity-management": {
            level: "edit",
            additionalAccess: {
              suspendEntity: true,
            },
          },
        }),
      },
      {
        id: "rl-003",
        type: "Custom",
        name: "Outlet Manager",
        members: "5 members",
        membersList: [
          { id: "mbr-004", name: "Lisa Manager", email: "lisa.manager@restaurant.com", status: "Active" },
          { id: "mbr-005", name: "James Staff", email: "james.staff@restaurant.com", status: "Active" },
          { id: "mbr-006", name: "Emma Invited", email: "emma.invited@restaurant.com", status: "Invited" },
          { id: "mbr-007", name: "Robert Inactive", email: "robert.inactive@restaurant.com", status: "Locked" },
          { id: "mbr-008", name: "Patricia Staff", email: "patricia.staff@restaurant.com", status: "Active" },
        ],
        description: "Handles outlet setup, catalog upkeep, and operational device access.",
        status: "Active",
        updated: "28 Mar 2026",
        permissions: createRolePermissions({
          "entity-management": "view",
          catalog: "full",
          category: "edit",
          unit: "edit",
          modifier: "edit",
          device: "edit",
          "grouped-device": "edit",
          "table-management": "full",
          "device-management": "full",
          cashier: "edit",
          "printer-settings": "edit",
        }),
      },
      {
        id: "rl-004",
        type: "Custom",
        name: "Kitchen Lead",
        members: "3 members",
        membersList: [
          { id: "mbr-009", name: "Chef David", email: "david.chef@restaurant.com", status: "Active" },
          { id: "mbr-010", name: "Cook Alex", email: "alex.cook@restaurant.com", status: "Invited" },
          { id: "mbr-011", name: "Sous Chef Tom", email: "tom.sous@restaurant.com", status: "Locked" },
        ],
        description: "Oversees kitchen display workflows and printer coordination.",
        status: "Inactive",
        updated: "19 Mar 2026",
        permissions: createRolePermissions({
          catalog: "view",
          category: "view",
          modifier: "view",
          device: "view",
          "printer-settings": "edit",
        }),
      },
      {
        id: "rl-005",
        type: "Custom",
        name: "Cashier Supervisor",
        members: "4 members",
        membersList: [
          { id: "mbr-012", name: "Cashier Lead", email: "lead.cashier@restaurant.com", status: "Active" },
          { id: "mbr-013", name: "Register Op", email: "register.op@restaurant.com", status: "Active" },
          { id: "mbr-014", name: "New Cashier", email: "new.cashier@restaurant.com", status: "Invited" },
          { id: "mbr-015", name: "Old Cashier", email: "old.cashier@restaurant.com", status: "Locked" },
        ],
        description: "Monitors POS access, cashier operations, and receipt printer setup.",
        status: "Active",
        updated: "15 Mar 2026",
        permissions: createRolePermissions({
          catalog: "view",
          category: "view",
          unit: "view",
          cashier: {
            level: "edit",
            additionalAccess: { approveVoid: true },
          },
          "printer-settings": "edit",
        }),
      },
      {
        id: "rl-006",
        type: "Custom",
        name: "Audit Viewer",
        members: "6 members",
        membersList: [
          { id: "mbr-016", name: "Auditor Prime", email: "auditor.prime@restaurant.com", status: "Active" },
          { id: "mbr-017", name: "Auditor Second", email: "auditor.second@restaurant.com", status: "Active" },
          { id: "mbr-018", name: "Auditor Third", email: "auditor.third@restaurant.com", status: "Active" },
          { id: "mbr-019", name: "Pending Auditor", email: "pending.auditor@restaurant.com", status: "Invited" },
          { id: "mbr-020", name: "Former Auditor", email: "former.auditor@restaurant.com", status: "Locked" },
          { id: "mbr-021", name: "Temp Auditor", email: "temp.auditor@restaurant.com", status: "Locked" },
        ],
        description: "Read-only access for compliance reviews and operational visibility.",
        status: "Active",
        updated: "10 Mar 2026",
        permissions: createRolePermissions({
          "user-management": "view",
          "role-management": "view",
          "entity-management": "view",
          catalog: "view",
          category: "view",
          unit: "view",
          modifier: "view",
          device: "view",
          "grouped-device": "view",
          "table-management": "view",
          "device-management": "view",
          cashier: "view",
          "kitchen-display-system": "view",
          "printer-settings": "view",
        }),
      },
    ],
    "device-management": [
      {
        id: "dm-006",
        deviceName: "Kitchen Printer A",
        pairingCode: "PRT - 2207 - 018",
        deviceType: "Printer",
        status: "Connected",
        deviceConnected: "Samsung Galaxy Tab S8, iPad (9th Gen)",
        connectedDevices: ["Waiter Tablet B", "Cashier Tablet A"],
        deviceOs: "Firmware 3.1",
        lastActive: "24 Apr 2026, 15:18",
        addedBy: "Natasha Smith",
        addedByName: "Natasha Smith",
        addedByRole: "Owner",
      },
      {
        id: "dm-007",
        deviceName: "Front Printer B",
        pairingCode: "PRT - 2207 - 019",
        deviceType: "Printer",
        status: "Connected",
        deviceConnected: "iPad (9th Gen), Samsung Galaxy Tab S7, Samsung Galaxy Tab S8",
        connectedDevices: ["Cashier Tablet A", "Kitchen Tablet 01", "Waiter Tablet B"],
        deviceOs: "Firmware 3.0",
        lastActive: "24 Apr 2026, 15:20",
        addedBy: "Natasha Smith",
        addedByName: "Natasha Smith",
        addedByRole: "Owner",
      },
      {
        id: "dm-008",
        deviceName: "Back Printer C",
        pairingCode: "PRT - 2207 - 020",
        deviceType: "Printer",
        status: "Connected",
        deviceConnected: "iPad (9th Gen), Samsung Galaxy Tab S7, Samsung Galaxy Tab S8, Epson TM-T88VI",
        connectedDevices: ["Cashier Tablet A", "Kitchen Tablet 01", "Waiter Tablet B", "Kitchen Printer A"],
        deviceOs: "Firmware 2.8",
        lastActive: "24 Apr 2026, 15:22",
        addedBy: "Natasha Smith",
        addedByName: "Natasha Smith",
        addedByRole: "Owner",
      },
      {
        id: "dm-001",
        deviceName: "Cashier Tablet A",
        pairingCode: "TSH - 4921 - 285",
        deviceType: "Point of Sales (POS)",
        status: "Connected",
        deviceConnected: "Epson TM-T88VI",
        connectedDevices: ["Front Printer B"],
        deviceOs: "iPadOS 17",
        lastActive: "24 Apr 2026, 15:12",
        addedBy: "Natasha Smith",
        addedByName: "Natasha Smith",
        addedByRole: "Owner",
      },
      {
        id: "dm-002",
        deviceName: "Kitchen Tablet 01",
        pairingCode: "KDS - 1205 - 442",
        deviceType: "Kitchen Display System (KDS)",
        status: "Connected",
        deviceConnected: "Star TSP143III",
        connectedDevices: ["Kitchen Printer A"],
        deviceOs: "Android 13",
        lastActive: "24 Apr 2026, 14:55",
        addedBy: "Natasha Smith",
        addedByName: "Natasha Smith",
        addedByRole: "Owner",
      },
      {
        id: "dm-004",
        deviceName: "Waiter Tablet B",
        pairingCode: "TSH - 3192 - 118",
        deviceType: "Point of Sales (POS)",
        status: "Connected",
        deviceConnected: "Brother QL-820NWB",
        connectedDevices: ["Kitchen Printer A"],
        deviceOs: "Android 14",
        lastActive: "24 Apr 2026, 15:10",
        addedBy: "Natasha Smith",
        addedByName: "Natasha Smith",
        addedByRole: "Owner",
      },
      {
        id: "dm-003",
        deviceName: "Cashier Dual Screen A",
        pairingCode: "POS - 8823 - 910",
        deviceType: "Point of Sales (POS)",
        status: "Disconnected",
        deviceConnected: null,
        connectedDevices: [],
        deviceOs: null,
        lastActive: "22 Apr 2026, 09:30",
        addedBy: "Natasha Smith",
        addedByName: "Natasha Smith",
        addedByRole: "Owner",
      },
      {
        id: "dm-005",
        deviceName: "Self-Service Kiosk A",
        pairingCode: "ADM - 5501 - 229",
        deviceType: "Kiosk",
        status: "Connected",
        deviceConnected: "Epson TM-m30",
        connectedDevices: ["Back Printer C"],
        deviceOs: "Android 10",
        lastActive: "24 Apr 2026, 15:00",
        addedBy: "Natasha Smith",
        addedByName: "Natasha Smith",
        addedByRole: "Owner",
      },
    ],
    "grouped-device": [
      {
        id: "gd-001",
        name: "Kitchen Group",
        deviceList: ["dm-006", "dm-002"],
        catalogList: ["cat-002", "cat-003"],
      },
    ],
    dashboardOrders: [
      {
        id: "ord-1012",
        guest: "Table 08",
        total: 685000,
        channel: "Dine In",
        status: "Completed",
      },
      {
        id: "ord-1013",
        guest: "GrabFood #A12",
        total: 245000,
        channel: "Delivery",
        status: "Preparing",
      },
      {
        id: "ord-1014",
        guest: "Table 15",
        total: 425000,
        channel: "Dine In",
        status: "Queued",
      },
      {
        id: "ord-1015",
        guest: "GoFood #D77",
        total: 310000,
        channel: "Delivery",
        status: "Completed",
      },
    ],
  };
}

export function createInitialSearchState() {
  return {
    catalog: "",
    category: "",
    "dashboard-report-detail": "",
    modifier: "",
    unit: "",
    "pricing-rule": "",
    "selling-time": "",
    "business-unit": "",
    "user-list": "",
    "role-access": "",
    "device-management": "",
    "grouped-device": "",
  };
}

export function createInitialFiltersState() {
  return {
    catalog: { category: [], sellingTime: [], availability: "All" },
    category: { sellingTime: [] },
    modifier: {},
    unit: {},
    "pricing-rule": {},
    "selling-time": {},
    "business-unit": { status: "All" },
    "user-list": { status: "All", role: "All" },
    "role-access": { status: "All" },
    "device-management": { deviceType: [], status: [] },
    "grouped-device": {},
  };
}

export function createInitialRowsPerPageState() {
  return {
    catalog: 25,
    category: 25,
    "dashboard-report-detail": 25,
    modifier: 25,
    unit: 25,
    "pricing-rule": 25,
    "selling-time": 25,
    "business-unit": 25,
    "user-list": 25,
    "role-access": 25,
    "device-management": 25,
    "grouped-device": 25,
  };
}

export function createInitialPageState() {
  return {
    catalog: 1,
    category: 1,
    "dashboard-report-detail": 1,
    modifier: 1,
    unit: 1,
    "pricing-rule": 1,
    "selling-time": 1,
    "business-unit": 1,
    "user-list": 1,
    "role-access": 1,
    "device-management": 1,
    "grouped-device": 1,
  };
}

export function createInitialSelectedRowsState() {
  return {
    catalog: [],
    category: [],
    modifier: [],
    unit: [],
    "pricing-rule": [],
    "selling-time": [],
    "business-unit": [],
    "user-list": [],
    "role-access": [],
    "device-management": [],
    "grouped-device": [],
  };
}

