import { formatDayMonth, shiftDateByDays, DASHBOARD_REPORT_TIME_RANGE_OPTIONS } from "../constants/dashboard.js";
import { formatDashboardReportDate, formatDashboardReportDateValue, parseDashboardReportDateValue, formatIdr } from "./dashboardDateUtils.js";
import { createDashboardSalesOrderRows } from "./dashboardTrendBucketUtils.js";
import { createInventoryReportDetail } from "./inventoryReportUtils.jsx";

export function createSalesReportDetailDefinitions(unitName, businessUnitNames = []) {
  const salesAndOrderRows = createDashboardSalesOrderRows(
    new Date(),
    businessUnitNames
  );
  const inventoryReportDetail = createInventoryReportDetail(unitName);

  return {
    "sales-orders": {
      id: "sales-orders",
      kind: "sales-orders",
      title: "Sales & Orders Report",
      copy: `Detailed sales and order records for ${unitName}.`,
      summary: [
        ["Entity", unitName],
        ["Period", "Today"],
        ["Primary View", "By Item / By Transaction"],
      ],
      itemColumns: [
        { key: "catalog", label: "Catalog" },
        { key: "totalOrders", label: "Total Order", align: "right", sortable: true, sortKey: "totalOrdersValue" },
        { key: "discountApplied", label: "Discount", align: "right", sortable: true, sortKey: "totalDiscountValue" },
        { key: "taxCollected", label: "Tax", align: "right", sortable: true, sortKey: "totalTaxValue" },
        { key: "totalGrossSales", label: "Total Gross Sales", align: "right", sortable: true, sortKey: "totalGrossSalesValue" },
        { key: "totalNetSales", label: "Total Net Sales", align: "right", sortable: true, sortKey: "totalNetSalesValue" },
      ],
      orderColumns: [
        {
          key: "dateTime",
          label: "Date",
          contentClassName: "dashboard-report-detail__date-time",
          sortable: true,
        },
        { key: "transactionId", label: "Transaction ID" },
        { key: "businessUnit", label: "Entity", sortable: true },
        { key: "shift", label: "Shift" },
        { key: "staff", label: "Staff" },
        { key: "orderType", label: "Order Type" },
        { key: "payment", label: "Payment" },
        { key: "discountApplied", label: "Discount", align: "right", sortable: true, sortKey: "discountAppliedValue" },
        { key: "taxCollected", label: "Tax", align: "right", sortable: true, sortKey: "taxCollectedValue" },
        {
          key: "totalTransaction",
          label: "Total Transaction",
          align: "right",
          sortable: true,
          sortKey: "totalTransactionValue",
        },
        { key: "status", label: "Status", type: "status" },
      ],
      rows: salesAndOrderRows,
    },
    "inventory-report": inventoryReportDetail,
    "average-order-value": {
      id: "average-order-value",
      title: "Average Order Value Report",
      copy: `Average order value breakdown for ${unitName}.`,
      summary: [
        ["Entity", unitName],
        ["Period", "This Week"],
        ["AOV", formatIdr(64500)],
      ],
      columns: [
        { key: "date", label: "Date" },
        { key: "orders", label: "Orders", align: "right" },
        { key: "netSales", label: "Net Sales", align: "right" },
        { key: "aov", label: "AOV", align: "right" },
      ],
      rows: [
        {
          id: "aov-1",
          date: "3 Apr 2026",
          orders: "251",
          netSales: formatIdr(15872000),
          aov: formatIdr(63200),
        },
        {
          id: "aov-2",
          date: "4 Apr 2026",
          orders: "268",
          netSales: formatIdr(17152000),
          aov: formatIdr(64000),
        },
        {
          id: "aov-3",
          date: "5 Apr 2026",
          orders: "274",
          netSales: formatIdr(17646000),
          aov: formatIdr(64400),
        },
        {
          id: "aov-4",
          date: "6 Apr 2026",
          orders: "281",
          netSales: formatIdr(18115000),
          aov: formatIdr(64500),
        },
        {
          id: "aov-5",
          date: "7 Apr 2026",
          orders: "286",
          netSales: formatIdr(18450000),
          aov: formatIdr(64500),
        },
      ],
    },
    "discount-summary": {
      id: "discount-summary",
      title: "Discount Report",
      copy: `Discount usage and nominal discount breakdown for ${unitName}.`,
      summary: [
        ["Entity", unitName],
        ["Period", "Today"],
        ["Total Discount", "42 Applied / " + formatIdr(1285000)],
      ],
      columns: [
        { key: "discountName", label: "Discount Name" },
        { key: "qty", label: "Discount Applied (qty)", align: "right", sortable: true, sortKey: "appliedQtyValue" },
        { key: "nominal", label: "Amount Discount", align: "right", sortable: true, sortKey: "amountDiscountedValue" },
      ],
      rows: [
        {
          id: "discount-1",
          discountName: "Happy Hour Beverage",
          qty: "14",
          nominal: formatIdr(420000),
        },
        {
          id: "discount-2",
          discountName: "Lunch Combo",
          qty: "11",
          nominal: formatIdr(315000),
        },
        {
          id: "discount-3",
          discountName: "Member Refill",
          qty: "9",
          nominal: formatIdr(210000),
        },
        {
          id: "discount-4",
          discountName: "Weekend Bundle",
          qty: "5",
          nominal: formatIdr(190000),
        },
        {
          id: "discount-5",
          discountName: "Dessert Pairing",
          qty: "3",
          nominal: formatIdr(150000),
        },
      ],
    },
    "refund-transaction": {
      id: "refund-transaction",
      title: "Refund Transaction Report",
      copy: `Refund records and nominal refund amounts for ${unitName}.`,
      summary: [
        ["Entity", unitName],
        ["Period", "Today"],
        ["Refund Summary", "7 Refunds / " + formatIdr(285000)],
      ],
      columns: [
        { key: "date", label: "Date" },
        { key: "transactionId", label: "Transaction ID" },
        { key: "staff", label: "Staff" },
        { key: "reason", label: "Reason" },
        { key: "nominal", label: "Nominal", align: "right" },
      ],
      rows: [
        {
          id: "refund-1",
          date: "9 Apr 2026",
          transactionId: "TRX-260409-011",
          staff: "Natasha Smith",
          reason: "Wrong item served",
          nominal: formatIdr(48000),
        },
        {
          id: "refund-2",
          date: "9 Apr 2026",
          transactionId: "TRX-260409-023",
          staff: "Rendy Saputra",
          reason: "Delayed beverage",
          nominal: formatIdr(36000),
        },
        {
          id: "refund-3",
          date: "9 Apr 2026",
          transactionId: "TRX-260409-038",
          staff: "Salsa Mahendra",
          reason: "Order cancellation",
          nominal: formatIdr(52000),
        },
        {
          id: "refund-4",
          date: "9 Apr 2026",
          transactionId: "TRX-260409-061",
          staff: "Dio Ramadhan",
          reason: "Promo mismatch",
          nominal: formatIdr(74000),
        },
      ],
    },
    "void-transaction": {
      id: "void-transaction",
      title: "VOID Transaction Report",
      copy: `VOID records and nominal void amounts for ${unitName}.`,
      summary: [
        ["Entity", unitName],
        ["Period", "Today"],
        ["VOID Summary", "5 VOID / " + formatIdr(124000)],
      ],
      columns: [
        { key: "date", label: "Date" },
        { key: "transactionId", label: "Transaction ID" },
        { key: "staff", label: "Staff" },
        { key: "reason", label: "Reason" },
        { key: "nominal", label: "Nominal", align: "right" },
      ],
      rows: [
        {
          id: "void-1",
          date: "9 Apr 2026",
          transactionId: "TRX-260409-017",
          staff: "Natasha Smith",
          reason: "Modifier mismatch",
          nominal: formatIdr(26000),
        },
        {
          id: "void-2",
          date: "9 Apr 2026",
          transactionId: "TRX-260409-041",
          staff: "Rendy Saputra",
          reason: "Double input",
          nominal: formatIdr(18000),
        },
        {
          id: "void-3",
          date: "9 Apr 2026",
          transactionId: "TRX-260409-052",
          staff: "Salsa Mahendra",
          reason: "Kitchen reject",
          nominal: formatIdr(34000),
        },
        {
          id: "void-4",
          date: "9 Apr 2026",
          transactionId: "TRX-260409-073",
          staff: "Kevin Pratama",
          reason: "POS correction",
          nominal: formatIdr(46000),
        },
      ],
    },
    "cancelled-orders": {
      id: "cancelled-orders",
      title: "Cancelled Orders Report",
      copy: `Cancelled order activity for ${unitName}.`,
      summary: [
        ["Entity", unitName],
        ["Period", "Today"],
        ["Cancelled Orders", "9 Orders"],
      ],
      columns: [
        { key: "date", label: "Date" },
        { key: "transactionId", label: "Transaction ID" },
        { key: "staff", label: "Staff" },
        { key: "orderType", label: "Order Type" },
        { key: "reason", label: "Reason" },
      ],
      rows: [
        {
          id: "cancelled-1",
          date: "9 Apr 2026",
          transactionId: "TRX-260409-014",
          staff: "Natasha Smith",
          orderType: "Delivery",
          reason: "Customer unreachable",
        },
        {
          id: "cancelled-2",
          date: "9 Apr 2026",
          transactionId: "TRX-260409-026",
          staff: "Rendy Saputra",
          orderType: "Take Away",
          reason: "Duplicate transaction",
        },
        {
          id: "cancelled-3",
          date: "9 Apr 2026",
          transactionId: "TRX-260409-047",
          staff: "Salsa Mahendra",
          orderType: "Dine In",
          reason: "Guest request",
        },
        {
          id: "cancelled-4",
          date: "9 Apr 2026",
          transactionId: "TRX-260409-082",
          staff: "Kevin Pratama",
          orderType: "Pickup",
          reason: "Payment timeout",
        },
      ],
    },
    "tax-collected": {
      id: "tax-collected",
      title: "Tax Collected Report",
      copy: `Collected tax records for ${unitName}.`,
      summary: [
        ["Entity", unitName],
        ["Period", "Today"],
        ["Tax Collected", formatIdr(1677000)],
      ],
      columns: [
        { key: "date", label: "Date" },
        { key: "taxableSales", label: "Taxable Sales", align: "right" },
        { key: "taxType", label: "Tax Type" },
        { key: "taxRate", label: "Tax Rate", align: "right" },
        { key: "taxCollected", label: "Tax Collected", align: "right" },
      ],
      rows: [
        {
          id: "tax-1",
          date: "9 Apr 2026",
          taxableSales: formatIdr(4825000),
          taxType: "PPN",
          taxRate: "11%",
          taxCollected: formatIdr(530750),
        },
        {
          id: "tax-2",
          date: "9 Apr 2026",
          taxableSales: formatIdr(3180000),
          taxType: "PPN",
          taxRate: "11%",
          taxCollected: formatIdr(349800),
        },
        {
          id: "tax-3",
          date: "9 Apr 2026",
          taxableSales: formatIdr(2745000),
          taxType: "PPN",
          taxRate: "11%",
          taxCollected: formatIdr(301950),
        },
        {
          id: "tax-4",
          date: "9 Apr 2026",
          taxableSales: formatIdr(2795000),
          taxType: "PPN",
          taxRate: "11%",
          taxCollected: formatIdr(307450),
        },
        {
          id: "tax-5",
          date: "9 Apr 2026",
          taxableSales: formatIdr(1700000),
          taxType: "PPN",
          taxRate: "11%",
          taxCollected: formatIdr(187000),
        },
      ],
    },
  };
}

